### PR TITLE
fix root file breaking when updating with remix-pwa

### PR DESCRIPTION
**Pull request by dev-afzalansari**
closes: #72 

This PR will add a custom hook in the `sw-hook` file in the `app/utils/client` directory as discussed in #72 and when the command is executed, in `root` an import statement for `useSWEffect`  and the `useSWEffect()` instead of the hook itself will be added.

Now the cli only needs to check if there is an import statement for `useSWEffect` and if the hook is called from the `root`. Hence no content will be repeated.

### CODE REVIEW

**Review by ShafSpecs — APPROVED** [review]
Perfect 👍

**Comment by ShafSpecs** [comment]
You beat me to implement this too =)

**Comment by dev-afzalansari** [comment]
@ShafSpecs,

>You beat me to implement this too =)

😄Hope you are doing well.

**Comment by ShafSpecs** [comment]
@dev-afzalansari Yep, doing much better. Thanks ❤️

**Pull request merged**
